config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
   get 'edit' , to: 'users#edit'
  put 'update', to: 'users#update'
  
  get 'startpickup', to: 'users#startpickup'
  post 'users/pickup', to: 'users#pickup'
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  resources :users do
    member do
      get :followings, :followers, :search, :pickup, :favorite, :pickup_show
    end
  end
  
   resources :posts do
    member do
      get :followed
    end
   end
  
  resources :favorites, only: [:create, :show, :destroy]
  
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :symptoms

  get 'symptoms/fail_new' => 'symptom#fail_new'

  
  get '*anything' => 'errors#routing_error'
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    mount_uploader :picture, PictureUploader
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, presence: true
    validates :sex, presence: true
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    validates :symptoms, length: { maximum: 20 }
    validate :picture_size
    
    has_secure_password
    has_many :posts
    has_many :following_relationships, class_name: "Relationship",
                                       foreign_key: "follower_id",
                                       dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    has_many :follower_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    has_many :ownerships, foreign_key: "user_id", dependent: :destroy
    has_many :symptoms , through: :ownerships
    
    has_many :favorites, foreign_key: "user_id", dependent: :destroy
    has_many :favposts, through: :favorites, source: :_ollowedpost
    
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    def following?(other_user)
        following_users
        .include?(other_user)
    end
    
    def feed_items
       Post.where(user_id: following_user_ids + [self.id])
    end
    
    
    def own(user, symp_id)
        Ownership.find_or_create_by(user_id: user.id, symptom_id: symp_id)
    end
    
    private
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
   # def active?
    #    start_date <= Date.today &&
   #       (end_date.nil? || end_date > Date.today)
   # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :followings, :followers,]
  before_action :correct_user, only: [:edit, :update, :following, :followers, :search,]
  #before_action :check_account
  before_action :check_timeout
  
  def new
    @user = User.new
  end
  
  
  def create
    @user = User.new(user_params)
    s_array = params[:user][:ownerships]
    
    if @user.save
      flash[:success] = "Welcome to symptoms!"
      s_array.each do |s_id|
        if s_id != ""
          @user.own(@user, s_id.to_i)
        end
      end
    redirect_to @user
   else
     render 'new'
    end
  end
  
  def show
   
    @user = User.find(params[:id])
    @posts = Kaminari.paginate_array(@user.posts.order(created_at: :desc)).page(params[:page]).per(10)
    @symptoms = @user.symptoms
    
    # my_symptoms = current_user.symptoms
     
   
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @users = Kaminari.paginate_array(@user.following_users(params[:followed_id])).page(params[:page]).per(10)
    @symptom = @user.symptoms
    @users.each do |u|
    @symptoms = u.symptoms
    end
    #@users.delete(@user.id)
  end
  
  def followers
    @user = User.find(params[:id])
    @users =  Kaminari.paginate_array(@user.follower_users(params[:follower_id])).page(params[:page]).per(10)
     @symptom = @user.symptoms
     @users.each do |u|
    @symptoms = u.symptoms
    end
    #@users.delete(@user.id)
  end
  
  def search
    my_symptoms = current_user.symptoms.pluck(:id)
    
    #他のユーザーをtargetにidだけ拾ってくる
    target = Array.new
    my_symptoms.each do |e|
         target = (target + Ownership.where(symptom_id: e).pluck(:user_id))
         @target = target.group_by(&:to_i).sort_by{|_,v|-v.size}.map(&:first)  #同じ症状を持っている人を、一致した症状の数が多い順に並べる

  # 自分とフォローしている人は除く
  #  target.uniq!  #重複削除
    #targetは症状を持っている人IDの配列
    
     @target.delete(current_user.id)
     # @user = User.find(@target).index_by(&:id).slice(*@target).values
     @users = Kaminari.paginate_array(
                    User.find(@target).index_by(&:id).slice(*@target).values
                  ).page(params[:page]).per(10)
     end
     
  end
  
  def startpickup
    @symptom = Symptom.new
  end
  
  def pickup
  
        my_symptoms = params[:symptom][:ownerships]
        my_symptoms.delete("") #投稿フォームから空文字列がゴミで入るので除去Sym
        my_symptoms.compact!
        @my_symptoms = my_symptoms.map(&:to_i)
        
        
        
        other_symptoms = []
        if request.post? then
          
          a = params[:symptom][:name]
          
          if a.present?
            @other_symptom = Symptom.where('name like ?',"%#{a}%")
            other_symptoms = @other_symptom.pluck(:id)
         # else
          #  other_symptoms = nil
        #  end
     end
   end
        @pickup_symptoms = @my_symptoms.push(other_symptoms).flatten!
        @pickup_symptoms.uniq!
        
        target = Array.new
         my_symptoms.push(other_symptoms).flatten!.each do |e|
         target = target + Ownership.where(symptom_id: e).pluck(:user_id)
         @target = target.group_by(&:to_i).sort_by{|_,v|-v.size}.map(&:first)
       
    #targetは症状を持っている人IDの配列
    
    
     @users = Kaminari.paginate_array(
       User.find(@target).index_by(&:id).slice(*@target).values
       ).page(params[:page]).per(10)
     end
  end

  
  private
  
   def user_params
    params.require(:user).permit(:name, :age, :sex, :email, :password,
                                 :password_confirmation, :picture, {:symptoms => []})
   end
  
  def correct_user
    @user = User.find(params[:id])
    if @user !=current_user
      redirect_to root_url
    end
  end
  
  # def check_account
  #  if current_user && !current_user.active?
  #    session.delete(:user_id)
  #    flash.alert = "アカウントが無効になりました。"
  #    redirect_to root_path
  #  end
  # end
  
   TIMEOUT = 2.minutes
  
   def check_timeout
    if current_user
      if session[:last_access_time] >= TIMEOUT.ago
        session[:last_access_time] = Time.current
      else
        session.delete(user_id: current_user.id)
        flash[:alert] = "セッションがタイムアウトしました。"
        redirect_to new_session_path
      end
    end
   end
end

app/helpers/user_helper.rb
module UserHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
    def current_user
        if session[:user_id]
          @current_user || User.find_by(id: session[:user_id])
        elsif cookies.signed[:user_id]
          @current_user || User.find_by_id_and_auto_login_token(
              cookies.signed[:user_id],cookies.signed[:auto_login_token])
        end
    end
    
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-success" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user !=@user %>
  <div id="follow_form"> 
      <% if current_user.following?(@user) %>
         <%= render 'unfollow' %>
      <% else %>
         <%= render 'follow' %>
      <% end %>
  </div>
 <% end %>

app/views/users/_form.html.erb
<%= form_for(@user, :html=>{class:"form-horizontal"}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
        <div class="col-md-2"></div>
            <%= f.label :"名前", class:"col-md-2 control-label" %>
        <div class="col-md-4">
            <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="col-md-4"></div>
    </div>
    
    <div class="form-group">
        <div class="col-md-2"></div>
            <%= f.label :"年齢", class:"col-md-2 control-label"  %>
        <div class="col-md-2">
            <%= f.text_field :age, class:"form-control" %>
        </div>
        <div class="col-md-6"></div>
    </div>  
    
    <div class="form-group"> 
        <div class="col-md-2"></div>
            <%= f.label :"性別", class:"col-md-2 control-label"  %>
        <div class="col-md-2">
            <%= f.select :sex, ['男性', '女性'], { include_blank: '選択してください' } %>
        </div>
        <div class="col-md-6"></div>
    </div>  
    
    <div class="form-group">    
        <div class="col-md-2"></div>
            <%= f.label :"emailアドレス", class:"col-md-2 control-label"  %>
        <div class="col-md-4">
            <%= f.text_field :email, class:"col-md-10 form-control" %>
            <p class="help-block">半角文字で入力してください</p>
        </div>
        <div class="col-md-4"></div>
    </div>  
    
    <div class="form-group">    
        <div class="col-md-2"></div>
            <%= f.label :"パスワード", class:"col-md-2 control-label"  %>
        <div class="col-md-4">
            <%= f.password_field :password, class:"form-control" %>
        </div>
        <div class="col-md-4"></div>
    </div>  
    
    <div class="form-group">   
        <div class="col-md-2"></div>
            <%= f.label :"パスワード確認", class:"col-md-2 control-label"  %>
        <div class="col-md-4">
            <%= f.password_field :password_confirmation, class:"col-md-10 form-control" %>
        </div>
        <div class="col-md-4"></div>
     </div>
     
     <div class="form-group">
         <div class="col-md-2"></div>
             <%= f.label :"プロフィール画像", class: "col-md-2 control-label" %>
         <div class="col-md-6">
             <span class="picture">
　                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
　           </span>
         </div>
         <div class="col-md-2"></div>
     </div>
  
     
     <div class="form-group">
           <div class="col-md-1"></div>
               <%= f.label :symptoms, "あなたを悩ませているのは？" , class: "col-md-3 control-label"%>
           <div class="col-md-6">
               <%= f.collection_check_boxes(:ownerships, Symptom.all,:id,:name) do |s| %>
               <%= s.label { s.check_box + s.text } %>
            <% end %></br>
            </div>
            <div class="col-md-2"></div>
     </div>
            
            <%#  POPUP WIndows 表示で症状追加 %>
     <div class="form-group">
           <div class="col-md-2"></div>
           <div class="col-md-6">
            その他にお困りなら<%= link_to("こちら",
                {:controller => 'symptoms', :action => 'new'},
                {:onclick=>"window.open(this.href, 'new_symptom', 'height=200, width=800');return false;" })
            %>
           </div>
           <div class="col-md-4"></div>
     </div>
     <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/users/_relationship.html.erb
<% if @users == nil %>
    <h1 style="margin-top: 100px">"お探しのユーザーは見つかりません。"</h1>
<% else %>
<div class="container" style="margin-top: 30px">
    <% my_symptoms = current_user.symptoms %>
    <%= page_entries_info @users %>
     <div class="container-inner inner-default clearfix">
         <% @users.each do |user| %>
         <div class="row well">
            <div class="col-md-1">
                <% if user.picture? %>
                    <%= image_tag user.picture.url, :size =>'80x80'%>
                <% else %>
                    <%= gravatar_for(user) %>
                <% end %>
              <div class="action clearfix">
                <%= link_to "Profile", user_path(user.id), class: "btn btn-info" %>
              </div>
            </div>
            <div class="col-md-4">
               <%= user.name %></br>
               <%= user.age %>歳</br>
               <%= user.sex %></br>
               <% user.symptoms.each do |symptom| %>
                  <% if my_symptoms.include?(symptom) %>
                      <span class="strong"> <%= symptom.name %></span>
                  <% else %>
                      <span> <%= symptom.name %></span>
                  <% end %>
               <% end %>
            </div>
            <% if user.posts.any? %>
        　　　　最近の投稿
               <div class="col-md-6" style="background-color: #FFFFDD">
                 <% user.posts.order(created_at: :desc).limit(1).each do |p| %>
                 <%= p.content %>
                 <% end %>
               </div>
             <% end %>
            </div>
        <% end %>
    </div>
    <%= paginate @users %>
</div>
<% end %>

app/views/users/_relationships.html.erb
<div class="row">
    <aside class="col-md-4">
        <section class="user-info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %></br>
                <%= @user.age %>歳</br>
                <%= @user.sex %></br>
            </h1>
            <span>
               <% @symptom.each do |symptom| %>
                  <% if current_user.symptoms.include?(symptom) %>
                    <span class="strong"> <%= symptom.name %></span>
                  <% else %>
                    <span> <%= symptom.name %></span>
                  <% end %>
                <% end %>
            </span>
        </section>
    </aside>
    
    <% if @users.any? %>
        <div class="col-md-8">
             <%= page_entries_info @users %>
        <table class="table">
        <% @users.each do |user| %>
              <div id="users follow" class="container-fluid well" style="padding-bottom: 10px">
                <div class="col-md-4">
                 <%= gravatar_for user %>
                 <%= user.name %></br>
                 <%= user.age %>歳</br>
                 <%= user.sex %></br>
                 <% @symptoms.each do |symptom| %>
                  <% if current_user.symptoms.include?(symptom) %>
                    <span class="strong"> <%= symptom.name %></span>
                  <% else %>
                    <span> <%= symptom.name %></span>
                  <% end %>
                <% end %>
                 <div class="action clearfix">
                  <%= link_to "Profile", user_path(user.id), class: "btn btn-info" %>
                 </div>
                </div>
                 <% if user.posts.any? %>
                 <div class="col-md-6 well" style="background-color: white">
                    <% user.posts.order(created_at: :desc).limit(1).each do |p| %>
                    <%= p.content %>
                    <% end %>
                 </div>
                 <% end %>
              </div>
        <% end %>
        </table>
         <%= paginate @users %>
        </div>
    <% end %>
 </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id), 
             html: { method: :delete },
             remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid" style="margin-top: 60px">
<h1> アカウント編集 </h1>

<%= render 'form' %>
</div>

app/views/users/followers.html.erb
 <div style="margin-top: 50px" id="btn">
      <% if logged_in? %>
        <% if params[:controller] == 'sessions' && params[:action] == 'show' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'create' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'new' %>
        <% else %>
            <%= render 'shared/btn' %>
        <% end %>
        <% else %>
      <% end %>
    </div>
<h1 class="page-header" style="margin-top: 80px">フォロワー</h1>

<%= render 'relationship' %>

app/views/users/followings.html.erb
 <div style="margin-top: 50px" id="btn">
      <% if logged_in? %>
        <% if params[:controller] == 'sessions' && params[:action] == 'show' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'create' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'new' %>
        <% else %>
            <%= render 'shared/btn' %>
        <% end %>
        <% else %>
      <% end %>
    </div>

<h1 class="page-header" style="margin-to: 80px">フォロー</h1>

<%= render 'relationship' %>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

<h1>
    <%= gravatar_for @user %>
    <%= @user.name %><br>
    <%= @user.age %>
</h1>

app/views/users/new.html.erb
<div class="container-fluid well" style="margin-top: 60px">
<h1>新規登録</h1>

<%= render 'form' %>

</div>

app/views/users/search.html.erb
<div class="container-fluid" style="margin-top: 80px">
     <div id="btn">
      <% if logged_in? %>
        <% if params[:controller] == 'sessions' && params[:action] == 'show' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'create' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'new' %>
        <% else %>
            <%= render 'shared/btn' %>
        <% end %>
        <% else %>
      <% end %>
    </div>
<div class="row">
<div class="col-md-12">
<% if @users == nil %>
    <h1 style="margin-top: 100px">"お探しのユーザーは見つかりません。"</h1>
<% else %>
    <% my_symptoms = current_user.symptoms %>
    <%= page_entries_info @users %>
     <div class="container-inner inner-default clearfix">
         <% @users.each do |user| %>
         <div class="row well">
            <div class="col-md-2">
              <% if user.picture? %>
                <%= image_tag user.picture.url, :size =>'80x80'%>
              <% else %>
                <%= gravatar_for(user) %>
              <% end %>
              <div class="action clearfix">
                <%= link_to "Profile", user_path(user.id), class: "btn btn-info" %>
              </div>
            </div>
            <div class="col-md-4">
               <%= user.name %></br>
               <%= user.age %>歳</br>
               <%= user.sex %></br>
               <% user.symptoms.each do |symptom| %>
                  <% if my_symptoms.include?(symptom) %>
                      <span class="strong"> <%= symptom.name %></span>
                  <% else %>
                      <span> <%= symptom.name %></span>
                  <% end %>
               <% end %>
            </div>
            <% if user.posts.any? %>
        　　　　最近の投稿
               <div class="col-md-6" style="background-color: #FFFFDD">
                 <% user.posts.order(created_at: :desc).limit(1).each do |p| %>
                 <%= p.content %>
                 <% end %>
               </div>
             <% end %>
            </div>
        <% end %>
    </div>
    <%= paginate @users %>
</div>
<% end %>
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="row" style="margin-top: 60px">
    <aside class="col-md-4">
        <section class="user-info">
          <h1>
              <% if @user.picture? %>
                  <%= image_tag @user.picture.url, :size =>'80x80'%>
              <% else %>
                  <%= gravatar_for @user %>
              <% end %>
             <%= @user.name %></br>
             <%= @user.age %>歳</br>
          </h1>
            <span>
                <% @symptoms.each do |symptom| %>
                  <% if logged_in? %>
                    <% if current_user.symptoms.include?(symptom) %>
                      <span class="strong"> <%= symptom.name %></span>
                    <% else %>
                      <span> <%= symptom.name %></span>
                    <% end %>
                  <% else %>
                    <%= symptom.name %>
                  <% end %>
                <% end %>
            </span></br>
           <span>
            <%= @user.following_users.count %>
            <%= link_to "フォロー", followings_user_path %>
           </span>
           <span>
             <%= @user.follower_users.count %>
             <%= link_to "フォロワー", followers_user_path %>
           </span>
        </section>
         <div class="col-md-4">
             <% if logged_in? %>
             <%= render 'follow_form' %>
             <% else %>
             <%= link_to "Log_in", login_path, class: "btn btn-primary" %>
             <% end %>
           </div>
        <div>
          <% if @user == current_user %>
              <%= link_to "戻る", session_path(current_user.id), method: :get, class: "btn btn-primary" %>
          <% else %>
              <%= link_to "戻る", search_user_path, class: "btn btn-primary" %>
          <% end %>
        </div>
    </aside>
    <div class="col-md-8">
        <% if @user.posts.any? %>
        <h3>"投稿" (<%= @user.posts.count %>)</h3>
        <ul class="post list-unstyled">
            <%= page_entries_info @posts %>
            <%= render @posts %>
            <%= paginate @posts %>
        </ol>
        <% end %>
    </div>
</div>

app/views/users/startpickup.html.erb
 <div style="margin-top: 80px" id="btn">
      <% if logged_in? %>
        <% if params[:controller] == 'sessions' && params[:action] == 'show' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'create' %>
        <% elsif params[:controller] == 'sessions' && params[:action] == 'new' %>
        <% else %>
            <%= render 'shared/btn' %>
        <% end %>
        <% else %>
      <% end %>
    </div>

<div class="container-fluid well" style="margin-top:150px">
<div class="container-fluid" style="margin-top: 120px">
  <div class="form-group">
    <div class="col-md-2"></div>
    <div class="col-md-8">
          <%= form_for(@symptom, url:{action:"pickup", controller:"users"}, html:{class:"form-horizontal"}) do |f| %>
          <%= f.label :symptoms, "お困りなのは？" %>
          <%= f.collection_check_boxes(:ownerships, Symptom.all,:id,:name) do |s| %>
                <%= s.label { s.check_box + s.text } %>
          <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="form-group">
      <dic class="col-md-4 text-right">
          <%= f.label :name, "症状名" %>
      </div>
      <div class="col-md-4">
          <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-4"></div>
  </div>
  <div class="form-group" style="margin-top: 30px">
      <div class="col-md-4"></div>
      <div class="col-md-4">
          <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
     <div class="col-md-4"></div>
<% end %>
</div></br>
<div class="container" style="margin-top: 30px; margin-bottom: 80px">
  <div class="col-md-8"></div>
  
  <div class="col-md-2"></div>
</div>
</div>