config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
   get 'edit' , to: 'users#edit'
  put 'update', to: 'users#update'
  
  get 'startpickup', to: 'users#startpickup'
  post 'users/pickup', to: 'users#pickup'
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  resources :users do
    member do
      get :followings, :followers, :search, :pickup, :favorite, :pickup_show
    end
  end
  
   resources :posts do
    member do
      get :followed
    end
   end
  
  resources :favorites, only: [:create, :show, :destroy]
  
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :symptoms

  get 'symptoms/fail_new' => 'symptom#fail_new'

  
  get '*anything' => 'errors#routing_error'
end

app/views/shared/_btn.html.erb
<div class="container">
<div class="col-md-6"></div>
<div class="col-md-6">
<ul class="list-inline">
         <li class="list-group-item list-group-item-success"> <%= link_to "TOPへ", session_path(current_user.id) %></li>
     <% unless params[:action] == "search" %>
         <li class="list-group-item list-group-item-success"> <%= link_to "my症状", search_user_path(current_user.id)%></li>
     <% end %>
     
     <% unless params[:action] == "startpickup" %>
         <li class="list-group-item list-group-item-success"><%= link_to "他症状" , startpickup_path %></li>
     <% end %>
 
     <% unless params[:action] == "followings" %>   
         <li class="list-group-item list-group-item-success"> <%= link_to "フォロー",followings_user_path(current_user.id) %></li>
     <% end %>
 
     <% unless params[:action] == "followers" %>    
         <li class="list-group-item list-group-item-success"><%= link_to "フォロワー", followers_user_path(current_user.id)%></li>
     <% end %>
 
     <% unless params[:controller] == "favorites" %>    
         <li class="list-group-item list-group-item-success"><%= link_to "お気に入り", favorite_path(current_user.id)%></li>
     <% end %>
 
     <% unless params[:action] == "followed" %>    
         <li class="list-group-item list-group-item-success"> <%= link_to "お気に入られ",followed_post_path(current_user.id)%></li>
     <% end %>
</ul>
</div>
</div>


 

app/views/shared/_error_essages.html.erb
<% if object.error.any? %>
 <div id="error_explanation">
     <div class="alert alert-danger">
         The form contains <%= pluralize(object.error.count, "error") %>
     </div>
     <ul>
         <% object.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
     </ul>
 </div>
 <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
     <div class="alert alert-danger">
         The form contains <%= pluralize(object.errors.count, "error") %>
     </div>
     <ul>
         <% object.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
     </ul>
 </div>
 <% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
      <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_post_form.html.erb
<%= @post = Post.new unless @post %>
<%= form_for(@post, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
    <%= f.text_area :content, placeholder: "Compose new post" %>
<span class="image">
<%= f.file_field :image, :multiple => true, accept: 'image/jpeg,image/gif,image/png' %>
</spen>
<span>
    <%= f.submit "Post", class: "btn btn-primary" %>
</span>
<% end %>

<script type="text/javascript">
  ${'#post_image'}.bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5){
          alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "My profile", current_user %></span><br>
<span><%= pluralize(current_user.posts.count, "posts") %></span>

<script type="text/javascript">
  ${'#user_picture'}.bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5){
          alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
  });
</script>