config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
   get 'edit' , to: 'users#edit'
  put 'update', to: 'users#update'
  
  get 'startpickup', to: 'users#startpickup'
  post 'users/pickup', to: 'users#pickup'
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  resources :users do
    member do
      get :followings, :followers, :search, :pickup, :favorite, :pickup_show
    end
  end
  
   resources :posts do
    member do
      get :followed
    end
   end
  
  resources :favorites, only: [:create, :show, :destroy]
  
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :symptoms

  get 'symptoms/fail_new' => 'symptom#fail_new'

  
  get '*anything' => 'errors#routing_error'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="background-color: white">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle", data-toggle="collapse", data-target="#miniNav">
                <span class="sr-only">ナビゲーション</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
                <span class="icon-bar"></span>
        </button>
        <%= link_to "Let's share the health", "#", id: "logo" %>
      </div>
        <nav>
            <div class="collapse navbar-collapse", id="miniNav">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "ホーム", root_path %></li>
                <li><%= link_to "ヘルプ", "#" %></li>
                <li><%= link_to "お問い合わせ", inquiry_path %></li>
              <% if logged_in? %>
                <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
                <li class="dropkdown">
                    <a herf="#" class="dropdown-toggle" data-toggle="dropdown">
                        アカウント<b class="caret"></b>
                    </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "プトフィール", current_user %></li>
                    <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li> 
                </ul>
                </li>
              <% else %>
                <li><%= link_to "ログイン", login_path %></li>
              <% end %>
            </ul>
            </div>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Symptoms</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
<%= render 'layouts/header' %>

<div class="container">
   <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>
</div>
<div class="footer">
    <%= link_to "当サイトの利用規約", "#" %></br>
    &copy; 2016
</div>
</body>
</html>

app/views/layouts/symptoms.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Symptoms</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  
<%= yield %>
</div>
</body>
</html>